Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2018-12, with the labels that each got.

#169 K8s
  .gitignore
  CHANGELOG.md
  digitalocean/datasource_digitalocean_kubernetes_cluster.go
  digitalocean/datasource_digitalocean_kubernetes_cluster_test.go
  digitalocean/provider.go
  digitalocean/resource_digital_ocean_kuberentes_node_pool.go
  digitalocean/resource_digital_ocean_kubernetes_node_pool_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitialocean_kubernetes_cluster_test.go
  examples/kubernetes/main.tf
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/CONTRIBUTING.md
  vendor/github.com/digitalocean/godo/domains.go
  vendor/github.com/digitalocean/godo/droplets.go
  vendor/github.com/digitalocean/godo/firewalls.go
  vendor/github.com/digitalocean/godo/floating_ips.go
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/load_balancers.go
  vendor/github.com/digitalocean/godo/projects.go
  vendor/github.com/digitalocean/godo/storage.go
  vendor/github.com/digitalocean/godo/strings.go
  vendor/github.com/digitalocean/godo/tags.go
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
  vendor/vendor.json
  website/digitalocean.erb
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: dependencies, size/XXL

#172 Correct Kubernetes example
  examples/kubernetes/main.tf
Labels: size/XS

#173 Updated documentation after feedback from Terraform team
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/XS

#174 fix typo
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XS

#175 Fix typo and format in docs
  website/docs/d/volume.html.md
  website/docs/d/volume_snapshot.html.md
Labels: documentation, size/XS
