Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2018-08, with the labels that each got.

#97 When IPv6 and/or private networking are not enabled, default their addresses to "".
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_droplet_test.go
Labels: bug, needs-review

#94 Don't panic when enabling private_networking or ipv6. (Fixes #67)
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_droplet_test.go
Labels: bug, crash, needs-review

#95 Set resize_disk to the default value on import.
  digitalocean/resource_digitalocean_droplet.go
Labels: bug, needs-review

#122 Added the ability to create a domain without specifying the initial IP address
  digitalocean/resource_digitalocean_domain.go
  digitalocean/resource_digitalocean_domain_test.go
  website/docs/r/domain.html.markdown
Labels: size/M

#121 Added missing functionality/configuration to the `digitalocean_record` resource
  digitalocean/resource_digitalocean_record.go
  digitalocean/resource_digitalocean_record_test.go
  website/docs/r/record.html.markdown
Labels: size/XL

#120 Migrated tags to use sets and centralised tag definitions/functionality
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_firewall.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_tag.go
  digitalocean/resource_digitalocean_tag_test.go
  digitalocean/set.go
  digitalocean/suppress.go
  digitalocean/suppress_test.go
  digitalocean/tags.go
  digitalocean/tags_test.go
Labels: size/L

#125 Added support for volume resizing
  digitalocean/resource_digitalocean_volume.go
  digitalocean/resource_digitalocean_volume_test.go
  website/docs/r/volume.markdown
Labels: size/L

#127 Added validations with minor optimizations to the load balancer resource
  digitalocean/loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer.go
  website/docs/r/loadbalancer.html.markdown
Labels: size/L

#128 Updated the state representation of the `user_data` droplet property to a hashed one
  digitalocean/hash.go
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_droplet_test.go
  website/docs/r/droplet.html.markdown
Labels: size/L

#132 Enable setting a dns' record weight to 0 (updated godo SDK)
  digitalocean/resource_digitalocean_record_test.go
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/account.go
  vendor/github.com/digitalocean/godo/domains.go
  vendor/github.com/digitalocean/godo/godo.go
  vendor/vendor.json
Labels: size/M
