Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-03, with the labels that each got.

#194 fix typo: remove extra word
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/XS

#195 Fix typo in node pool name
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XS

#196 [MODULES] Updating digitalocean/godo to latest version
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/CONTRIBUTING.md
  vendor/github.com/digitalocean/godo/cdn.go
  vendor/github.com/digitalocean/godo/databases.go
  vendor/github.com/digitalocean/godo/doc.go
  vendor/github.com/digitalocean/godo/domains.go
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/images.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/load_balancers.go
  vendor/github.com/digitalocean/godo/projects.go
  vendor/github.com/digitalocean/godo/storage.go
  vendor/github.com/digitalocean/godo/tags.go
  vendor/github.com/tent/http-link-go/.gitignore
  vendor/github.com/tent/http-link-go/.travis.yml
  vendor/github.com/tent/http-link-go/LICENSE
  vendor/github.com/tent/http-link-go/README.md
  vendor/github.com/tent/http-link-go/link.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#168 Acceptance test sweeper improvements
  digitalocean/datasource_digitalocean_droplet_snapshot_test.go
  digitalocean/datasource_digitalocean_droplet_test.go
  digitalocean/datasource_digitalocean_loadbalancer_test.go
  digitalocean/datasource_digitalocean_record_test.go
  digitalocean/resource_digitalocean_certificate_test.go
  digitalocean/resource_digitalocean_domain_test.go
  digitalocean/resource_digitalocean_droplet_snapshot_test.go
  digitalocean/resource_digitalocean_droplet_test.go
  digitalocean/resource_digitalocean_firewall_test.go
  digitalocean/resource_digitalocean_floating_ip_assignment_test.go
  digitalocean/resource_digitalocean_loadbalancer_test.go
  digitalocean/resource_digitalocean_volume_snapshot_test.go
  digitalocean/resource_digitalocean_volume_test.go
Labels: size/L

#198 r/digitalocean_database_cluster: Adding new resource to manage database clusters
  digitalocean/provider.go
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  website/digitalocean.erb
  website/docs/r/database_cluster.html.markdown
Labels: documentation, new-resource, size/XL

#201 Update Firewall docs to be 0.12-beta compatible (Fixes #200).
  website/docs/r/firewall.html.markdown
Labels: documentation, size/S

#199 Add support for enabling PROXY Protocol on Load Balancers.
  digitalocean/datasource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer_test.go
  website/docs/r/loadbalancer.html.markdown
Labels: documentation, enhancement, size/M
