Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-07, with the labels that each got.

#262 K8s: Do not filter out node pool tags also applied to the cluster (Fixes: #184).
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
Labels: size/M

#264 provider: Add the ability to set DIGITALOCEAN_ACCESS_TOKEN
  digitalocean/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#267 Support enabling and disabling backups on Droplets (Fixes: #266).
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_droplet_test.go
Labels: size/M

#270 Allow Databases to have URNs for use with Projects
  digitalocean/datasource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/CONTRIBUTING.md
  vendor/github.com/digitalocean/godo/README.md
  vendor/github.com/digitalocean/godo/databases.go
  vendor/github.com/digitalocean/godo/droplets.go
  vendor/github.com/digitalocean/godo/firewalls.go
  vendor/github.com/digitalocean/godo/go.mod
  vendor/github.com/digitalocean/godo/go.sum
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/load_balancers.go
  vendor/github.com/digitalocean/godo/projects.go
  vendor/github.com/digitalocean/godo/snapshots.go
  vendor/github.com/digitalocean/godo/storage.go
  vendor/github.com/digitalocean/godo/tags.go
  vendor/github.com/digitalocean/godo/vpcs.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/modules.txt
  website/docs/d/database_cluster.html.markdown
  website/docs/r/database_cluster.html.markdown
Labels: dependencies, documentation, size/XL

#271 Update digitalocean_kubernetes_cluster version
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XS

#273 Consistently protect against nil response in error handling (Fixes: #272).
  digitalocean/datasource_digitalocean_domain.go
  digitalocean/datasource_digitalocean_floating_ip.go
  digitalocean/datasource_digitalocean_image.go
  digitalocean/datasource_digitalocean_kubernetes_cluster.go
  digitalocean/datasource_digitalocean_record.go
  digitalocean/datasource_digitalocean_tag.go
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_domain.go
  digitalocean/resource_digitalocean_droplet_snapshot.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  digitalocean/resource_digitalocean_record.go
  digitalocean/resource_digitalocean_volume.go
  digitalocean/resource_digitalocean_volume_attachment.go
  digitalocean/resource_digitalocean_volume_snapshot.go
Labels: size/S
