Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-09, with the labels that each got.

#293 Added Tags support for database cluster
  digitalocean/datasource_digitalocean_database_cluster.go
  digitalocean/datasource_digitalocean_database_cluster_test.go
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/.travis.yml
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/README.md
  vendor/github.com/digitalocean/godo/databases.go
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/modules.txt
  website/docs/r/database_cluster.html.markdown
Labels: dependencies, documentation, size/L

#294 Added DatabaseReplica resource support
  digitalocean/import_digitalocean_database_replica_test.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_database_replica.go
  digitalocean/resource_digitalocean_database_replica_test.go
  website/docs/r/database_replica.html.markdown
Labels: documentation, size/XL

#290 Find a droplet by tag
  digitalocean/datasource_digitalocean_droplet.go
  digitalocean/datasource_digitalocean_droplet_test.go
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/d/droplet.html.md
Labels: dependencies, documentation, size/XXL

#295 terraform.VersionString() has been deprecated.
  digitalocean/config.go
  digitalocean/provider.go
Labels: size/S

#297 Document using doctl to grab k8s versions
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XS
