Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-05, with the labels that each got.

#228 Remove outdated info from Droplet tag docs.
  website/docs/r/droplet.html.markdown
Labels: documentation, size/XS

#232 Various resource import improvements (Fixes: #231).
  digitalocean/import_digitalocean_droplet_test.go
  digitalocean/import_digitalocean_record_test.go
  digitalocean/import_digitalocean_spaces_bucket_test.go
  digitalocean/import_digitalocean_volume_test.go
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_record.go
  digitalocean/resource_digitalocean_spaces_bucket.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  digitalocean/resource_digitalocean_volume.go
Labels: size/M

#241 ReadMe Typo
  README.md
Labels: size/XS
