Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-10, with the labels that each got.

#300 Provide private connection details for `database_cluster'
  digitalocean/datasource_digitalocean_database_cluster.go
  digitalocean/datasource_digitalocean_database_cluster_test.go
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  website/docs/r/database_cluster.html.markdown
Labels: documentation, size/S

#301 Mark uri, private_uri, password as sensitive for database_cluster.
  digitalocean/resource_digitalocean_database_cluster.go
Labels: size/XS

#302 Expose private connection info for replicas and mark final DBaaS fields sensitive
  digitalocean/datasource_digitalocean_database_cluster.go
  digitalocean/datasource_digitalocean_database_cluster_test.go
  digitalocean/resource_digitalocean_database_replica.go
  digitalocean/resource_digitalocean_database_replica_test.go
  website/docs/d/database_cluster.html.markdown
  website/docs/r/database_replica.html.markdown
Labels: documentation, size/S

#308 doks: fix acc tests
  digitalocean/datasource_digitalocean_kubernetes_cluster_test.go
  digitalocean/provider_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
Labels: documentation, size/S

#309 doks: bump to latest cluster version and use token auth
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/S

#312 doks: bump version in tests to 1.15.4-do.0
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XS

#313 Update Kubernetes examples to use tokens over certs.
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/XS

#315 doks: Produce a valid kubeconfig file.
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
Labels: documentation, size/M

#314 Update the documentation to v0.12 syntax (Fixes: #274).
  website/docs/d/database_cluster.html.markdown
  website/docs/d/domain.html.md
  website/docs/d/droplet.html.md
  website/docs/d/floating_ip.html.md
  website/docs/d/image.html.md
  website/docs/d/loadbalancer.html.md
  website/docs/d/record.html.md
  website/docs/d/ssh_key.html.md
  website/docs/d/tag.html.md
  website/docs/d/volume.html.md
  website/docs/d/volume_snapshot.html.md
  website/docs/r/cdn.html.markdown
  website/docs/r/certificate.html.markdown
  website/docs/r/domain.html.markdown
  website/docs/r/droplet_snapshot.html.markdown
  website/docs/r/firewall.html.markdown
  website/docs/r/floating_ip.html.markdown
  website/docs/r/floating_ip_assignment.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
  website/docs/r/loadbalancer.html.markdown
  website/docs/r/project.html.markdown
  website/docs/r/record.html.markdown
  website/docs/r/spaces_bucket.html.markdown
  website/docs/r/ssh_key.html.markdown
  website/docs/r/tag.html.markdown
  website/docs/r/volume.html.markdown
  website/docs/r/volume_attachment.html.markdown
  website/docs/r/volume_snapshot.html.markdown
Labels: documentation, size/L

#322 add support for spaces CORS
  digitalocean/resource_digitalocean_spaces_bucket.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  website/docs/r/spaces_bucket.html.markdown
Labels: documentation, size/XL

#323 Update .go-version to 1.12.9
  .go-version
  .travis.yml
Labels: size/XS

#326 Add missing sidebar link to digitalocean_database_replica resource page
  website/digitalocean.erb
Labels: documentation, size/XS

#324 Add data source for account
  digitalocean/datasource_digitalocean_account.go
  digitalocean/datasource_digitalocean_account_test.go
  digitalocean/provider.go
  website/digitalocean.erb
  website/docs/d/account.html.md
Labels: documentation, size/M

#328 Add resource for database user
  digitalocean/import_digitalocean_database_user_test.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_database_user.go
  digitalocean/resource_digitalocean_database_user_test.go
  website/digitalocean.erb
  website/docs/r/database_user.html.markdown
Labels: documentation, size/XL

#325 Add data source for sizes (with filter and sort)
  digitalocean/datasource_digitalocean_sizes.go
  digitalocean/datasource_digitalocean_sizes_test.go
  digitalocean/filter.go
  digitalocean/filter_test.go
  digitalocean/provider.go
  digitalocean/sort.go
  digitalocean/sort_test.go
  website/digitalocean.erb
  website/docs/d/sizes.html.md
Labels: documentation, size/XL

#307 doks: add node pool auto-scale fields
  digitalocean/datasource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  digitalocean/util.go
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/XL
