Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-12, with the labels that each got.

#338 Update project docs to include import example.
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#337 Add autoscaling examples to the K8s resources' docs.
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/S

#339 add support for volume snapshot tags
  digitalocean/datasource_digitalocean_volume_snapshot.go
  digitalocean/datasource_digitalocean_volume_snapshot_test.go
  digitalocean/resource_digitalocean_volume_snapshot.go
  digitalocean/resource_digitalocean_volume_snapshot_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/CONTRIBUTING.md
  vendor/github.com/digitalocean/godo/databases.go
  vendor/github.com/digitalocean/godo/doc.go
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/links.go
  vendor/github.com/digitalocean/godo/registry.go
  vendor/github.com/digitalocean/godo/tags.go
  vendor/modules.txt
  website/docs/d/volume_snapshot.html.md
  website/docs/r/volume_snapshot.html.markdown
Labels: dependencies, documentation, size/XL

#344 Fix default node pool tag comment
  digitalocean/resource_digitalocean_kubernetes_cluster.go
Labels: size/XS

#349 Don't store full certificate data in state file (Fixes: #156).
  digitalocean/hash.go
  digitalocean/resource_digitalocean_certificate.go
  digitalocean/resource_digitalocean_certificate_test.go
  digitalocean/resource_digitalocean_droplet.go
Labels: size/S

#348 Add support for Database Firewalls (Fixes :#340).
  digitalocean/import_digitalocean_database_firewall_test.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_database_firewall.go
  digitalocean/resource_digitalocean_database_firewall_test.go
  website/digitalocean.erb
  website/docs/r/database_firewall.html.markdown
Labels: documentation, size/XL

#341 Add digitalocean_kubernetes_versions data source.
  digitalocean/datasource_digitalocean_kubernetes_versions.go
  digitalocean/datasource_digitalocean_kubernetes_versions_test.go
  digitalocean/provider.go
  website/digitalocean.erb
  website/docs/d/kubernetes_versions.html.md
Labels: documentation, size/L

#346 Add support for Redis eviction policies (Fixes: #342).
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  website/docs/r/database_cluster.html.markdown
Labels: documentation, size/L

#347 Add support for configuring SQL mode.
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  website/docs/r/database_cluster.html.markdown
Labels: documentation, size/M

#353 add support for updating database cluster tags
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/action.go
  vendor/github.com/digitalocean/godo/balance.go
  vendor/github.com/digitalocean/godo/cdn.go
  vendor/github.com/digitalocean/godo/certificates.go
  vendor/github.com/digitalocean/godo/domains.go
  vendor/github.com/digitalocean/godo/droplets.go
  vendor/github.com/digitalocean/godo/firewalls.go
  vendor/github.com/digitalocean/godo/floating_ips.go
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/images.go
  vendor/github.com/digitalocean/godo/keys.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/load_balancers.go
  vendor/github.com/digitalocean/godo/meta.go
  vendor/github.com/digitalocean/godo/projects.go
  vendor/github.com/digitalocean/godo/regions.go
  vendor/github.com/digitalocean/godo/sizes.go
  vendor/github.com/digitalocean/godo/snapshots.go
  vendor/github.com/digitalocean/godo/storage.go
  vendor/github.com/digitalocean/godo/storage_actions.go
  vendor/github.com/digitalocean/godo/tags.go
  vendor/github.com/digitalocean/godo/vpcs.go
  vendor/modules.txt
Labels: dependencies, size/L
