Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-04, with the labels that each got.

#202 Certificates: Move attribute validation from CustomizeDiff to Create (Fixes: #163).
  digitalocean/resource_digitalocean_certificate.go
  digitalocean/resource_digitalocean_certificate_test.go
Labels: size/M

#205 Fix typo in k8s cluster resource test filename
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
Labels: size/XS

#209 Normalize case for region attribute across all resources
  digitalocean/datasource_digitalocean_droplet_snapshot.go
  digitalocean/datasource_digitalocean_volume.go
  digitalocean/datasource_digitalocean_volume_snapshot.go
  digitalocean/resource_digitalocean_floating_ip.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_spaces_bucket.go
  digitalocean/resource_digitalocean_volume.go
Labels: size/S

#210 Updates the spaces resource to expose the urn.
  digitalocean/resource_digitalocean_spaces_bucket.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  website/docs/r/spaces_bucket.html.markdown
Labels: documentation, size/XS

#211 Updates the floating ip resource to expose the urn.
  digitalocean/datasource_digitalocean_floating_ip.go
  digitalocean/datasource_digitalocean_floating_ip_test.go
  digitalocean/resource_digitalocean_floating_ip.go
  digitalocean/resource_digitalocean_floating_ip_test.go
  website/docs/d/floating_ip.html.md
  website/docs/r/floating_ip.html.markdown
Labels: documentation, size/XS

#213 Feature/introduce urn attribute to domain
  digitalocean/datasource_digitalocean_domain.go
  digitalocean/datasource_digitalocean_domain_test.go
  digitalocean/resource_digitalocean_domain.go
  digitalocean/resource_digitalocean_domain_test.go
  website/docs/d/domain.html.md
  website/docs/r/domain.html.markdown
Labels: documentation, size/XS

#214 Feature/introduce urn attribute to loadbalancer
  digitalocean/datasource_digitalocean_loadbalancer.go
  digitalocean/datasource_digitalocean_loadbalancer_test.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer_test.go
  website/docs/d/loadbalancer.html.md
  website/docs/r/loadbalancer.html.markdown
Labels: documentation, size/XS

#212 Feature/introduce urn attribute to volume
  digitalocean/datasource_digitalocean_volume.go
  digitalocean/datasource_digitalocean_volume_test.go
  digitalocean/resource_digitalocean_volume.go
  digitalocean/resource_digitalocean_volume_test.go
  website/docs/d/volume.html.md
  website/docs/r/volume.html.markdown
Labels: documentation, size/XS

#215 Feature/introduce urn attribute to droplet
  digitalocean/datasource_digitalocean_droplet.go
  digitalocean/datasource_digitalocean_droplet_test.go
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_droplet_test.go
  website/docs/d/droplet.html.md
  website/docs/r/droplet.html.markdown
Labels: documentation, size/XS

#217 Avoid drift when remote slug is updated
  digitalocean/resource_digitalocean_droplet.go
Labels: size/XS

#220 Documentation updates in preparation for release
  website/digitalocean.erb
  website/docs/r/cdn.html.markdown
  website/docs/r/certificate.html.markdown
  website/docs/r/droplet.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/L

#221 Update sidebar and fix typo.
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  website/digitalocean.erb
Labels: documentation, size/XS
