Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-11, with the labels that each got.

#333 digitalocean_kubernetes_cluster version changes
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  go.mod
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/validate.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: dependencies, size/XXL

#334 Add connection pool resource (Fixes: #225).
  digitalocean/import_digitalocean_database_connection_pool_test.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_database_connection_pool.go
  digitalocean/resource_digitalocean_database_connection_pool_test.go
  website/digitalocean.erb
  website/docs/r/database_connection_pool.html.markdown
  website/docs/r/database_replica.html.markdown
Labels: documentation, size/XL

#336 Add support for volume tags
  digitalocean/datasource_digitalocean_volume.go
  digitalocean/datasource_digitalocean_volume_test.go
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_volume.go
  digitalocean/resource_digitalocean_volume_test.go
  digitalocean/tags.go
  website/docs/d/volume.html.md
  website/docs/r/volume.html.markdown
Labels: documentation, size/M
