Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2019-06, with the labels that each got.

#248 Update cdn.html.markdown
  website/docs/r/cdn.html.markdown
Labels: documentation, size/XS

#247 Update spaces_bucket.html.markdown
  website/docs/r/spaces_bucket.html.markdown
Labels: documentation, size/XS

#249 Update floating_ip_assignment.html.markdown
  website/docs/r/floating_ip_assignment.html.markdown
Labels: documentation, size/XS

#250 Regenerate go.sum (Fixes: #246).
  go.sum
Labels: size/M

#252 resource/droplet: Removing the IPv6 private parameter
  digitalocean/resource_digitalocean_droplet.go
Labels: size/XS

#251 datasource: New Database Cluster Datasource
  digitalocean/datasource_digitalocean_database_cluster.go
  digitalocean/datasource_digitalocean_database_cluster_test.go
  digitalocean/provider.go
  website/digitalocean.erb
  website/docs/d/database_cluster.html.markdown
Labels: documentation, size/XL

#245 Remove Limited Availability mentions as Kubernetes is now in GA.
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/XS

#257 Fixed CAA record tag
  website/docs/r/record.html.markdown
Labels: documentation, size/XS
