Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2020-06, with the labels that each got.

#440 dbaas: Add support for specifying a VPC for read-only replicas.
  digitalocean/resource_digitalocean_database_replica.go
  digitalocean/resource_digitalocean_database_replica_test.go
Labels: size/M

#448 Add container_registry_docker_credentials to docs nav.
  website/digitalocean.erb
Labels: documentation, size/XS

#453 Fix vpc import syntax
  website/docs/r/vpc.html.markdown
Labels: documentation, size/XS

#450 Set ID in flattenDigitalOceanDroplet.
  digitalocean/datasource_digitalocean_droplets_test.go
  digitalocean/droplets.go
Labels: size/XS
