Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2020-04, with the labels that each got.

#407 add spaces_endpoint config to provider
  digitalocean/config.go
  digitalocean/provider.go
  digitalocean/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#406 support old volumes created with a dot in the name
  digitalocean/resource_digitalocean_volume.go
Labels: size/XS

#409 digitalocean_spaces_bucket: support bucket versioning
  digitalocean/resource_digitalocean_spaces_bucket.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  website/docs/r/spaces_bucket.html.markdown
Labels: documentation, size/L

#408 add digitalocean_spaces_bucket_object resource
  digitalocean/provider.go
  digitalocean/resource_digitalocean_spaces_bucket_object.go
  digitalocean/resource_digitalocean_spaces_bucket_object_test.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  go.mod
  website/digitalocean.erb
  website/docs/r/spaces_bucket_object.html.markdown
Labels: documentation, size/XXL

#412 Remove storage_class attribute from spaces_bucket_object.
  digitalocean/resource_digitalocean_spaces_bucket_object.go
  digitalocean/resource_digitalocean_spaces_bucket_object_test.go
  website/docs/r/spaces_bucket_object.html.markdown
Labels: documentation, size/M

#410 Add support for VPC.
  digitalocean/datasource_digitalocean_database_cluster.go
  digitalocean/datasource_digitalocean_database_cluster_test.go
  digitalocean/datasource_digitalocean_droplet.go
  digitalocean/datasource_digitalocean_droplet_test.go
  digitalocean/datasource_digitalocean_kubernetes_cluster.go
  digitalocean/datasource_digitalocean_kubernetes_cluster_test.go
  digitalocean/datasource_digitalocean_loadbalancer.go
  digitalocean/datasource_digitalocean_loadbalancer_test.go
  digitalocean/datasource_digitalocean_vpc.go
  digitalocean/datasource_digitalocean_vpc_test.go
  digitalocean/import_digitalocean_vpc_test.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  digitalocean/resource_digitalocean_droplet.go
  digitalocean/resource_digitalocean_droplet_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer_test.go
  digitalocean/resource_digitalocean_vpc.go
  digitalocean/resource_digitalocean_vpc_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/.travis.yml
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/CONTRIBUTING.md
  vendor/github.com/digitalocean/godo/README.md
  vendor/github.com/digitalocean/godo/billing_history.go
  vendor/github.com/digitalocean/godo/go.mod
  vendor/github.com/digitalocean/godo/go.sum
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/load_balancers.go
  vendor/github.com/digitalocean/godo/vpcs.go
  vendor/modules.txt
  website/digitalocean.erb
  website/docs/d/database_cluster.html.markdown
  website/docs/d/droplet.html.md
  website/docs/d/kubernetes_cluster.html.md
  website/docs/d/vpc.html.md
  website/docs/r/database_cluster.html.markdown
  website/docs/r/droplet.html.markdown
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/loadbalancer.html.markdown
  website/docs/r/vpc.html.markdown
Labels: dependencies, size/XXL

#411 digitalocean_spaces_bucket: add lifecycle_rule support
  digitalocean/resource_digitalocean_spaces_bucket.go
  digitalocean/resource_digitalocean_spaces_bucket_object.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  website/docs/r/spaces_bucket.html.markdown
Labels: documentation, size/XL

#413 spaces_bucket: Region attribute should be ForceNew.
  digitalocean/resource_digitalocean_spaces_bucket.go
Labels: size/XS

#417 fix transitive dependency in go.mod
  go.mod
  go.sum
Labels: size/XL

#416 add preliminary data sources for Spaces buckets
  digitalocean/datasource_digitalocean_spaces_bucket.go
  digitalocean/datasource_digitalocean_spaces_bucket_test.go
  digitalocean/datasource_digitalocean_spaces_buckets.go
  digitalocean/datasource_digitalocean_spaces_buckets_test.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_spaces_bucket_test.go
  digitalocean/spaces_buckets.go
  website/digitalocean.erb
  website/docs/d/spaces_bucket.html.md
  website/docs/d/spaces_buckets.html.md
Labels: documentation, size/XL

#420 add comment why spaces regions are hard-coded in data source
  digitalocean/spaces_buckets.go
Labels: size/S

#418 add digitalocean_droplets data source
  digitalocean/datasource_digitalocean_droplet.go
  digitalocean/datasource_digitalocean_droplets.go
  digitalocean/datasource_digitalocean_droplets_test.go
  digitalocean/droplets.go
  digitalocean/provider.go
  internal/datalist/schema.go
  website/digitalocean.erb
  website/docs/d/droplets.html.md
Labels: documentation, size/XL

#422 Fix handling of CAA records with iodef tag (fixes: #421).
  digitalocean/resource_digitalocean_record.go
  digitalocean/resource_digitalocean_record_test.go
Labels: size/S

#419 load balancers: Fix support for multiple forwarding rules (fixes: #414).
  digitalocean/datasource_digitalocean_loadbalancer.go
  digitalocean/datasource_digitalocean_loadbalancer_test.go
  digitalocean/loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer_test.go
Labels: size/L

#423 add digitalocean_spaces_bucket_object(s) data sources adapted from S3
  digitalocean/datasource_digitalocean_spaces_bucket_object.go
  digitalocean/datasource_digitalocean_spaces_bucket_object_test.go
  digitalocean/datasource_digitalocean_spaces_bucket_objects.go
  digitalocean/datasource_digitalocean_spaces_bucket_objects_test.go
  digitalocean/provider.go
  go.mod
  website/digitalocean.erb
  website/docs/d/spaces_bucket_object.html.md
  website/docs/d/spaces_bucket_objects.html.md
Labels: documentation, size/XXL

#425 Fixed incorrect data reference
  website/docs/d/vpc.html.md
Labels: documentation, size/XS
