Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2020-03, with the labels that each got.

#385 generic filter/sort framework for datasources
  digitalocean/datasource_digitalocean_region.go
  digitalocean/datasource_digitalocean_regions.go
  digitalocean/datasource_digitalocean_sizes.go
  digitalocean/datasource_digitalocean_sizes_test.go
  digitalocean/regions.go
  internal/datalist/filter.go
  internal/datalist/filter_test.go
  internal/datalist/schema.go
  internal/datalist/sort.go
  internal/datalist/sort_test.go
  internal/datalist/values.go
Labels: size/XXL

#391 add datasource for projects
  digitalocean/datasource_digitalocean_project.go
  digitalocean/datasource_digitalocean_project_test.go
  digitalocean/datasource_digitalocean_projects.go
  digitalocean/datasource_digitalocean_projects_test.go
  digitalocean/projects.go
  digitalocean/provider.go
  digitalocean/resource_digitalocean_project.go
  website/digitalocean.erb
  website/docs/d/project.html.md
  website/docs/d/projects.html.md
Labels: documentation, size/XL

#392 List all exported attributes for block storage volume
  website/docs/r/volume.html.markdown
Labels: documentation, size/XS

#394 add digitalocean_images datasource
  digitalocean/datasource_digitalocean_image.go
  digitalocean/datasource_digitalocean_image_test.go
  digitalocean/datasource_digitalocean_images.go
  digitalocean/datasource_digitalocean_images_test.go
  digitalocean/images.go
  digitalocean/provider.go
  go.mod
  website/digitalocean.erb
  website/docs/d/image.html.md
  website/docs/d/images.html.md
Labels: documentation, size/XL

#395 default digitalocean_image to user images
  digitalocean/datasource_digitalocean_image.go
  website/docs/d/image.html.md
Labels: documentation, size/XS

#393 Add support for MySQL user authentication management
  digitalocean/import_digitalocean_database_user_test.go
  digitalocean/resource_digitalocean_database_user.go
  digitalocean/resource_digitalocean_database_user_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/databases.go
  vendor/github.com/digitalocean/godo/go.sum
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/invoices.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/registry.go
  vendor/modules.txt
  website/docs/r/database_user.html.markdown
Labels: dependencies, documentation, size/XL

#382 Make DBaaS version required due to DigitalOcean API changes.
  digitalocean/resource_digitalocean_database_cluster.go
  digitalocean/resource_digitalocean_database_cluster_test.go
  website/docs/r/database_cluster.html.markdown
Labels: documentation, size/M

#396 add digitalocean_project_resources to bind resources to externally-managed projects
  digitalocean/provider.go
  digitalocean/resource_digitalocean_project.go
  digitalocean/resource_digitalocean_project_resources.go
  digitalocean/resource_digitalocean_project_resources_test.go
  website/digitalocean.erb
  website/docs/r/project_resources.html.markdown
Labels: documentation, size/XL

#398 fix some minor issues with recently-updated docs
  website/docs/d/image.html.md
  website/docs/d/images.html.md
  website/docs/d/project.html.md
  website/docs/d/projects.html.md
  website/docs/d/region.html.md
  website/docs/d/regions.html.md
  website/docs/d/sizes.html.md
Labels: documentation, size/M

#400 Fix volume name validation
  digitalocean/resource_digitalocean_volume.go
Labels: size/XS

#401 Do not error out if terraform:default-node-pool tag is missing when reading k8s cluster.
  digitalocean/import_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
Labels: size/XS

#402 Allow running KubernetesProviderInteroperability test locally.
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
Labels: size/XS

#403 Validate connection pool name
  digitalocean/resource_digitalocean_database_connection_pool.go
  digitalocean/resource_digitalocean_project.go
Labels: size/XS

#404 support volumes created before name rules changed
  digitalocean/resource_digitalocean_volume.go
Labels: size/XS
