Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2020-05, with the labels that each got.

#429 remove extra debug logging statement
  digitalocean/spaces_buckets.go
Labels: size/XS

#428 load balancers: Add support for backend keepalive (Fixes: #427).
  digitalocean/datasource_digitalocean_loadbalancer.go
  digitalocean/datasource_digitalocean_loadbalancer_test.go
  digitalocean/resource_digitalocean_loadbalancer.go
  digitalocean/resource_digitalocean_loadbalancer_test.go
  website/docs/r/loadbalancer.html.markdown
Labels: documentation, size/M

#431 Making SpacesAPI Endpoint optional
  digitalocean/provider.go
Labels: size/XS

#437 Fix arg in given example for resource spaces_bucket_object
  website/docs/r/spaces_bucket_object.html.markdown
Labels: documentation, size/XS

#439 fix: correct spelling
  digitalocean/resource_digitalocean_kubernetes_cluster.go
Labels: size/XS

#435 kubernetes: Fail faster on cluster create error (fixes: #434).
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
Labels: size/XS

#438 kubernetes: Re-work tests to no longer rely on hard-coded versions.
  digitalocean/datasource_digitalocean_kubernetes_cluster_test.go
  digitalocean/import_digitalocean_kubernetes_cluster_test.go
  digitalocean/import_digitalocean_kubernetes_node_pool_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
Labels: size/L

#444 Add forcenew to vpc_uuid field of kubernetes cluster resource
  digitalocean/resource_digitalocean_kubernetes_cluster.go
Labels: size/XS
