Repository digitalocean/terraform-provider-digitalocean, pull requests merged in 2020-02, with the labels that each got.

#369 Handle pagination for project resources (Fixes: #368).
  digitalocean/resource_digitalocean_project.go
  digitalocean/resource_digitalocean_project_test.go
Labels: size/M

#366 add droplet ID to node pools and droplet datasource
  digitalocean/datasource_digitalocean_droplet.go
  digitalocean/datasource_digitalocean_droplet_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  go.mod
  website/docs/d/droplet.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/M

#373 document use of @ as name on digitalocean_record
  website/docs/r/record.html.markdown
Labels: documentation, size/XS

#365 add import support for digitalocean_kubernetes_cluster and digitalocean_kubernetes_node_pool resources
  digitalocean/import_digitalocean_kubernetes_cluster_test.go
  digitalocean/import_digitalocean_kubernetes_node_pool_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: documentation, size/XL

#376 Update for deprecated terraform-plugin-sdk helper/validation methods.
  digitalocean/datasource_digitalocean_droplet_snapshot.go
  digitalocean/datasource_digitalocean_volume_snapshot.go
  digitalocean/resource_digitalocean_floating_ip.go
  digitalocean/resource_digitalocean_floating_ip_assignment.go
Labels: size/XS

#379 add labels support to Kubernetes node pools
  digitalocean/datasource_digitalocean_kubernetes_cluster.go
  digitalocean/datasource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_cluster.go
  digitalocean/resource_digitalocean_kubernetes_cluster_test.go
  digitalocean/resource_digitalocean_kubernetes_node_pool.go
  digitalocean/resource_digitalocean_kubernetes_node_pool_test.go
  go.mod
  go.sum
  vendor/github.com/digitalocean/godo/.whitesource
  vendor/github.com/digitalocean/godo/CHANGELOG.md
  vendor/github.com/digitalocean/godo/godo.go
  vendor/github.com/digitalocean/godo/kubernetes.go
  vendor/github.com/digitalocean/godo/registry.go
  vendor/modules.txt
  website/docs/d/kubernetes_cluster.html.md
  website/docs/r/kubernetes_cluster.html.markdown
  website/docs/r/kubernetes_node_pool.html.markdown
Labels: dependencies, documentation, size/L

#380 add digitalocean_regions and digitalocean_region data sources
  digitalocean/datasource_digitalocean_region.go
  digitalocean/datasource_digitalocean_region_test.go
  digitalocean/datasource_digitalocean_regions.go
  digitalocean/datasource_digitalocean_regions_test.go
  digitalocean/provider.go
  digitalocean/regions.go
  digitalocean/schema.go
  digitalocean/testing.go
  website/digitalocean.erb
  website/docs/d/region.html.md
  website/docs/d/regions.html.md
Labels: documentation, size/XL

#386 Require that volume names be lowercase and alphanumeric
  digitalocean/resource_digitalocean_volume.go
Labels: size/XS

#390 Typo correction in provider project docs
  website/docs/r/project.html.markdown
Labels: documentation, size/XS
